name: Deploy to Railway

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Railway
      uses: railway/deploy@v1
      with:
        service: ${{ secrets.RAILWAY_SERVICE_ID }}
        token: ${{ secrets.RAILWAY_TOKEN }}
        
    - name: Wait for deployment
      run: |
        echo "Waiting for Railway deployment to complete..."
        sleep 30
        
    - name: Health check
      run: |
        echo "Checking if backend is healthy..."
        curl -f "https://rork-study-buddy-production-eeeb.up.railway.app/health" || exit 1
